In [ ]:
# Author: LEITE, G. B. S.
# Description: Decision matrix normalization using the euclidean methodology
# Note: The function contained in this code return the normalized matrix transpose

In [ ]:
import numpy as np

In [ ]:
# Decision matrix definition
m = [[1.2, 25, 8, 58000, 7, 5, 1126],
     [1.65, 40, 7, 31000, 7, 8, 334],
     [1.27, 20, 9, 45000, 9, 6, 227],
     [1.77, 25, 7, 50000, 8, 8, 550]]
print(f'Decision matrix: {m}')

# Criterion status definition, so that: 0 corresponds to minimization criteria and 1 to maximization criteria
st = [0, 0, 1, 1, 1, 1, 0]
print(f'Criteria status: {st}')

Decision matrix: [[1.2, 25, 8, 58000, 7, 5, 1126], [1.65, 40, 7, 31000, 7, 8, 334], [1.27, 20, 9, 45000, 9, 6, 227], [1.77, 25, 7, 50000, 8, 8, 550]]
Criteria status: [0, 0, 1, 1, 1, 1, 0]


**Euclidean Normalization**

$x_{i j} = \frac{d_{ij}}{sqrt(\sum_{i=i}^n (d_{ij})^2)}$,  if the criterion is **maximization**. 

$x_{i j} = 1 - \frac{d_{ij}}{sqrt(\sum_{i=i}^n (d_{ij})^2)}$,  if the criterion is **minimization**.

Note: This normalization corrects the meanings of the criteria

In [6]:
def normalizar_euclidiana(matriz, status):
  """
  -> Function to calculate the Euclidean normalization of a decision matrix.

   :param matriz: decision matrix.
   :param status: list containing the status of each criterion - if it is a maxization criterion, the list receives 1 and, if it is a minization criterion, the list receives 0.
   :return: transposed normalized matrix.

  """
  
  l = []                                  # Generate the transposed matrix
  for j in range(len(matriz[0])):
    linha = []
    for i in range(len(matriz)):
      linha.append(matriz[i][j])
    l.append(linha)

  q = []                                   # Calculates the sum
  for linha in l:
    a = 0
    for item in linha:
      a += (item**2)
    b = (a**(1/2))
    q.append(b)
  
  m_final = []                             # Generate the normalized matrix
  for i in range(0, len(status)):
    lin = []
    if status[i] == 0:                     # This step evaluates whether the criterion is maximum or minimum
      for j in range(0, len(l[i])):        # The respective values are assigned to each item
        lin.append(1-(l[i][j]/q[i]))
      m_final.append(lin[:])
    
    else:                                  # And then the same steps are repeated for the maximum criteria.
      for j in range(0, len(l[i])):
        lin.append(l[i][j]/q[i])
      m_final.append(lin[:])
      
  return m_final

In [ ]:
# Function application
m_normec = np.array(normalizar_euclidiana(m, st))
print(f'Normalized matrix:\n{m_normec}')

Normalized matrix:
[[0.59794652 0.44717646 0.5744934  0.40697111]
 [0.56147099 0.29835358 0.64917679 0.56147099]
 [0.51320024 0.44905021 0.57735027 0.44905021]
 [0.61653304 0.32952628 0.4783446  0.531494  ]
 [0.44905021 0.44905021 0.57735027 0.51320024]
 [0.36369648 0.58191437 0.43643578 0.58191437]
 [0.1447731  0.74631813 0.82758747 0.58226039]]
