In [8]:
# Author: LEITE, G. B. S.
# Description: Decision matrix normalization using the sum methodology
# Note: The function contained in this code return the normalized matrix transpose

In [7]:
import numpy as np

In [9]:
# Decision matrix definition
m = [[1.2, 25, 8, 58000, 7, 5, 1126],
     [1.65, 40, 7, 31000, 7, 8, 334],
     [1.27, 20, 9, 45000, 9, 6, 227],
     [1.77, 25, 7, 50000, 8, 8, 550]]
print(f'Decision matrix: {m}')

# Criterion status definition, so that: 0 corresponds to minimization criteria and 1 to maximization criteria
st = [0, 0, 1, 1, 1, 1, 0]
print(f'Criteria status: {st}')

Decision matrix: [[1.2, 25, 8, 58000, 7, 5, 1126], [1.65, 40, 7, 31000, 7, 8, 334], [1.27, 20, 9, 45000, 9, 6, 227], [1.77, 25, 7, 50000, 8, 8, 550]]
Criteria status: [0, 0, 1, 1, 1, 1, 0]


**Sum Normalization Method**

$x_{i j} = \frac{d_{ij}}{\sum_{i=i}^n d_{ij}}$,  if the criterion is **maximization**. 

$x_{i j} = 1 - \frac{d_{ij}}{\sum_{i=i}^n d_{ij}}$,  if the criterion is **minimization**.

Note: This normalization corrects the meanings of the criteria

In [10]:
def normalizar_soma(matriz, status):
  """
  -> Function to calculate the sum normalization of a decision matrix.

   :param matriz: decision matrix.
   :param status: list containing the status of each criterion - if it is a maxization criterion, the list receives 1 and, if it is a minization criterion, the list receives 0.
   :return: transposed normalized matrix.

  """
  
  l = []                                  # Generate the transposed matrix
  for j in range(len(matriz[0])):
    linha = []
    for i in range(len(matriz)):
      linha.append(matriz[i][j])
    l.append(linha)

  q = []                                   # Calculates the sum
  for linha in l:
    a = 0
    for item in linha:
      a += item
    q.append(a)
  
  m_final = []                             # Generate the normalized matrix
  for i in range(0, len(status)):
    lin = []
    if status[i] == 0:                     # This step evaluates whether the criterion is maximum or minimum
      for j in range(0, len(l[i])):        # The respective values are assigned to each item
        lin.append(1-(l[i][j]/q[i]))
      m_final.append(lin[:])
    
    else:                                  # And then the same steps are repeated for the maximum criteria.
      for j in range(0, len(l[i])):
        lin.append(l[i][j]/q[i])
      m_final.append(lin[:])
      
  return m_final

In [11]:
# Function application
m_normsum = np.array(normalizar_soma(m, st))
print(f'Transposed normalized matrix:\n{m_normsum}')

Transposed normalized matrix:
[[0.79626486 0.71986418 0.78438031 0.69949066]
 [0.77272727 0.63636364 0.81818182 0.77272727]
 [0.25806452 0.22580645 0.29032258 0.22580645]
 [0.31521739 0.16847826 0.24456522 0.27173913]
 [0.22580645 0.22580645 0.29032258 0.25806452]
 [0.18518519 0.2962963  0.22222222 0.2962963 ]
 [0.4966473  0.85069289 0.89852481 0.754135  ]]
